#compdef pty
# zsh completion for pty — generated by `pty completions zsh`.
# Regenerate with: pty completions zsh > completions/pty.zsh
_pty() {
  local root="${PTY_ROOT:-${PTY_SESSION_DIR:-${HOME}/.local/state/pty}}"

  _pty_sessions() {
    local -a sessions
    if [[ -d "${root}" ]]; then
      sessions=(${root}/*.json(N:t:r))
    fi
    _describe 'session' sessions
  }

  local -a commands
  commands=(
    'run:Create a session and attach'
    'attach:Attach to an existing session'
    'a:Alias for attach'
    'machine-attach-v2:Headless framed duplex attach for terminal hosts'
    'exec:Replace the current session process'
    'peek:Print current screen (or follow / wait-for-text)'
    'send:Send text or key events'
    'events:Follow event log'
    'list:List sessions'
    'ls:Alias for list'
    'stats:Live CPU / memory / PIDs'
    'restart:SIGTERM + respawn'
    'kill:SIGTERM a running session'
    'recover:Rebind a supporting live daemon after registry unlink'
    'rm:Remove exited metadata'
    'remove:Alias for rm'
    'gc:Reconciliation pass'
    'tag:Read / write tags on one session'
    'tag-multi:Bulk tag ops across sessions'
    'emit:Publish a user.* event'
    'rename:Set / show / clear displayName'
    'metadata:Atomically patch presentation metadata by stable id'
    'up:Start sessions from pty.toml'
    'down:Stop sessions from pty.toml'
    'test:Run the pty test suite (vitest)'
    'remote-serve:Serve remote access control protocol'
  )

  _arguments -C \
    '(--root)--root[Pin PTY_ROOT for this call]:path:_directories' \
    '(--preselect-new)--preselect-new[TUI: pre-select "Create new session..."]:path:_directories' \
    '(--filter-tag)--filter-tag[TUI: filter to k=v (repeatable)]:path:_directories' \
    '1:command:->command' \
    '*::arg:->args'

  case $state in
    command)
      _describe 'command' commands
      ;;
    args)
      case ${words[1]} in
        run)
          _arguments \
            '(d --detach){d,--detach}[Create in the background (detached)]' \
            '(a --attach){a,--attach}[Create OR attach if id already exists]' \
            '(e --ephemeral){e,--ephemeral}[Ephemeral: auto-remove metadata on clean exit]' \
            '--id[Pin on-disk id (charset-validated)]' \
            '--name[Display label (trimmed, single-line, ≤ 160 Unicode scalars)]' \
            '--no-display-name[Skip the auto-generated label]' \
            '--tag[Tag session (k=v, repeatable)]' \
            '--env[Overlay child environment (KEY=VALUE, repeatable)]' \
            '--unset-env[Remove inherited environment key (repeatable)]' \
            '--cwd[Working directory]' \
            '--isolate-env[Scrub env to a safe allow-list]' \
            '--force[Create even from inside another pty]'
          ;;
        attach|a)
          _arguments \
            '(r --auto-restart){r,--auto-restart}[Auto-restart if the session is exited]' \
            '--no-restart[Attach only; never prompt or restart an exited session]' \
            '--force[Attach even from inside another pty]' \
            '--remote[Attach a session on a fabric peer]' \
            '--attach-stream-fd-v1[Write framed machine events to an inherited fd]:fd:' \
            '1:session:_pty_sessions'
          ;;
        machine-attach-v2)
          ;;
        exec)
          _arguments \
            '1:directory:_directories'
          ;;
        peek)
          _arguments \
            '(f --follow){f,--follow}[Follow output read-only]' \
            '--plain[Plain text (no ANSI)]' \
            '--full[Include full scrollback]' \
            '--wait[Wait until text appears]' \
            '(t --timeout){t,--timeout}[Timeout (seconds) for --wait]' \
            '--remote[Peek a session on a fabric peer]' \
            '1:session:_pty_sessions'
          ;;
        send)
          _arguments \
            '--seq[Ordered chunk / key event (repeatable)]' \
            '--with-delay[Delay between --seq items (sec)]' \
            '--paste[Wrap in bracketed-paste markers]' \
            '--remote[Send to a session on a fabric peer]' \
            '1:session:_pty_sessions'
          ;;
        events)
          _arguments \
            '--all[Follow every session, interleaved]' \
            '--recent[Print recent + exit]' \
            '--json[Emit JSON]' \
            '--wait[Wait for a specific event type]' \
            '(t --timeout){t,--timeout}[Timeout (seconds) for --wait]' \
            '1:session:_pty_sessions'
          ;;
        list|ls)
          _arguments \
            '--json[Emit JSON]' \
            '--tags[Include internal bookkeeping tags]' \
            '--filter-tag[Filter to k=v (repeatable, ALL match)]' \
            '--remote[Include remote sessions via pty-relay]' \
            '--status[Filter by status]:status:(running exited vanished)' \
            '--older-than[Only sessions older than a duration]' \
            '--newer-than[Only sessions newer than a duration]' \
            '--summary[One-line count summary instead of the list]'
          ;;
        stats)
          _arguments \
            '--json[Emit JSON]' \
            '--all[Include every session]' \
            '1:session:_pty_sessions'
          ;;
        restart)
          _arguments \
            '(y --yes){y,--yes}[Skip confirmation]' \
            '--force[Attach after restart even from inside another pty]' \
            '1:session:_pty_sessions'
          ;;
        kill)
          _arguments \
            '1:session:_pty_sessions'
          ;;
        recover)
          _arguments \
            '--snapshot[Captured capability-bearing metadata file]'
          ;;
        rm|remove)
          _arguments \
            '1:session:_pty_sessions'
          ;;
        gc)
          _arguments \
            '(n --dry-run){n,--dry-run}[Preview without changing anything]' \
            '--idle-days[Reap permanents with no attach in N days]' \
            '--fast-fail-window[Fast-fail window (seconds; default 60)]' \
            '--fast-fail-limit[Consecutive fast fails before flapping (default 3)]' \
            '--print-launchd-plist[Emit a launchd plist that runs pty gc]' \
            '--interval[Plist StartInterval seconds (default 30)]'
          ;;
        tag)
          _arguments \
            '--rm[Remove tag key (repeatable)]' \
            '1:session:_pty_sessions'
          ;;
        tag-multi)
          _arguments \
            '--all[Selector: every session]' \
            '--filter-tag[Selector: k=v (repeatable)]' \
            '--rm[Remove tag key (repeatable)]' \
            '--json[Emit JSON]' \
            '(y --yes){y,--yes}[Confirm --all + write]' \
            '1:session:_pty_sessions'
          ;;
        emit)
          _arguments \
            '--json[JSON payload]' \
            '--text[Text payload]' \
            '1:session:_pty_sessions'
          ;;
        rename)
          _arguments \
            '--show[Print current displayName]' \
            '--clear[Remove displayName]' \
            '1:session:_pty_sessions'
          ;;
        metadata)
          _arguments \
            '--id[Exact stable session id]' \
            '1:mode:(patch)'
          ;;
        up)
          _arguments \
            '1:directory:_directories'
          ;;
        down)
          _arguments \
            '1:directory:_directories'
          ;;
        test)
          _arguments \
            '--t[Run matching tests]' \
            '1:mode:(watch)'
          ;;
        remote-serve)
          _arguments \
            '--stdio[On-demand: serve one connection over stdio]' \
            '--socket[Listening daemon: bind a Unix socket]'
          ;;
      esac
      ;;
  esac
}

_pty "$@"
