# bash completion for pty — generated by `pty completions bash`.
# Regenerate with: pty completions bash > completions/pty.bash
_pty() {
  local cur prev commands
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  commands="run attach a machine-attach-v2 exec peek send events list ls stats restart kill recover rm remove gc tag tag-multi emit rename metadata up down test remote-serve"

  if [[ ${COMP_CWORD} -eq 1 ]]; then
    if [[ "${cur}" == -* ]]; then
      COMPREPLY=($(compgen -W "--root --preselect-new --filter-tag" -- "${cur}"))
    else
      COMPREPLY=($(compgen -W "${commands}" -- "${cur}"))
    fi
    return
  fi

  local root="${PTY_ROOT:-${PTY_SESSION_DIR:-${HOME}/.local/state/pty}}"
  local names=""
  if [[ -d "${root}" ]]; then
    names=$(ls "${root}"/*.json 2>/dev/null | xargs -I{} basename {} .json)
  fi

  case "${COMP_WORDS[1]}" in
    run)
      COMPREPLY=($(compgen -W "-d --detach -a --attach -e --ephemeral --id --name --no-display-name --tag --env --unset-env --cwd --isolate-env --force" -- "${cur}"))
      ;;
    attach|a)
      if [[ "${prev}" == "--attach-stream-fd-v1" ]]; then
        return
      fi
      if [[ "${cur}" == -* ]]; then
        COMPREPLY=($(compgen -W "-r --auto-restart --no-restart --force --remote --attach-stream-fd-v1" -- "${cur}"))
      else
        COMPREPLY=($(compgen -W "${names}" -- "${cur}"))
      fi
      ;;
    machine-attach-v2) ;;
    exec)
      COMPREPLY=($(compgen -o dirnames -- "${cur}"))
      ;;
    peek)
      if [[ "${cur}" == -* ]]; then
        COMPREPLY=($(compgen -W "-f --follow --plain --full --wait -t --timeout --remote" -- "${cur}"))
      else
        COMPREPLY=($(compgen -W "${names}" -- "${cur}"))
      fi
      ;;
    send)
      if [[ "${cur}" == -* ]]; then
        COMPREPLY=($(compgen -W "--seq --with-delay --paste --remote" -- "${cur}"))
      else
        COMPREPLY=($(compgen -W "${names}" -- "${cur}"))
      fi
      ;;
    events)
      if [[ "${cur}" == -* ]]; then
        COMPREPLY=($(compgen -W "--all --recent --json --wait -t --timeout" -- "${cur}"))
      else
        COMPREPLY=($(compgen -W "${names}" -- "${cur}"))
      fi
      ;;
    list|ls)
      COMPREPLY=($(compgen -W "--json --tags --filter-tag --remote --status --older-than --newer-than --summary" -- "${cur}"))
      ;;
    stats)
      if [[ "${cur}" == -* ]]; then
        COMPREPLY=($(compgen -W "--json --all" -- "${cur}"))
      else
        COMPREPLY=($(compgen -W "${names}" -- "${cur}"))
      fi
      ;;
    restart)
      if [[ "${cur}" == -* ]]; then
        COMPREPLY=($(compgen -W "-y --yes --force" -- "${cur}"))
      else
        COMPREPLY=($(compgen -W "${names}" -- "${cur}"))
      fi
      ;;
    kill)
      if [[ "${cur}" == -* ]]; then
        COMPREPLY=($(compgen -W "" -- "${cur}"))
      else
        COMPREPLY=($(compgen -W "${names}" -- "${cur}"))
      fi
      ;;
    recover)
      COMPREPLY=($(compgen -W "--snapshot" -- "${cur}"))
      ;;
    rm|remove)
      if [[ "${cur}" == -* ]]; then
        COMPREPLY=($(compgen -W "" -- "${cur}"))
      else
        COMPREPLY=($(compgen -W "${names}" -- "${cur}"))
      fi
      ;;
    gc)
      COMPREPLY=($(compgen -W "-n --dry-run --idle-days --fast-fail-window --fast-fail-limit --print-launchd-plist --interval" -- "${cur}"))
      ;;
    tag)
      if [[ "${cur}" == -* ]]; then
        COMPREPLY=($(compgen -W "--rm" -- "${cur}"))
      else
        COMPREPLY=($(compgen -W "${names}" -- "${cur}"))
      fi
      ;;
    tag-multi)
      if [[ "${cur}" == -* ]]; then
        COMPREPLY=($(compgen -W "--all --filter-tag --rm --json -y --yes" -- "${cur}"))
      else
        COMPREPLY=($(compgen -W "${names}" -- "${cur}"))
      fi
      ;;
    emit)
      if [[ "${cur}" == -* ]]; then
        COMPREPLY=($(compgen -W "--json --text" -- "${cur}"))
      else
        COMPREPLY=($(compgen -W "${names}" -- "${cur}"))
      fi
      ;;
    rename)
      if [[ "${cur}" == -* ]]; then
        COMPREPLY=($(compgen -W "--show --clear" -- "${cur}"))
      else
        COMPREPLY=($(compgen -W "${names}" -- "${cur}"))
      fi
      ;;
    metadata)
      COMPREPLY=($(compgen -W "--id" -- "${cur}"))
      ;;
    up)
      COMPREPLY=($(compgen -o dirnames -- "${cur}"))
      ;;
    down)
      COMPREPLY=($(compgen -o dirnames -- "${cur}"))
      ;;
    test)
      COMPREPLY=($(compgen -W "--t" -- "${cur}"))
      ;;
    remote-serve)
      COMPREPLY=($(compgen -W "--stdio --socket" -- "${cur}"))
      ;;
  esac
}
complete -F _pty pty
