# fish completions for pty — generated by `pty completions fish`.
# Regenerate with: pty completions fish > completions/pty.fish
# (kept in sync with src/cli.ts; see src/completions.ts)

function __pty_root
    if set -q PTY_ROOT
        echo $PTY_ROOT
    else if set -q PTY_SESSION_DIR
        echo $PTY_SESSION_DIR
    else
        echo "$HOME/.local/state/pty"
    end
end

function __pty_sessions
    set -l dir (__pty_root)
    if test -d "$dir"
        for f in $dir/*.json
            if test -f "$f"
                basename $f .json
            end
        end
    end
end

function __pty_needs_command
    set -l cmd (commandline -opc)
    test (count $cmd) -eq 1
end

function __pty_using_command
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 2; and test "$cmd[2]" = "$argv[1]"
end

complete -c pty -f

# ── Global flags ───────────────────────────────────────────────────────
complete -c pty -n __pty_needs_command -l root -x -d 'Pin PTY_ROOT for this call'
complete -c pty -n __pty_needs_command -l preselect-new -x -d 'TUI: pre-select "Create new session..."'
complete -c pty -n __pty_needs_command -l filter-tag -x -d 'TUI: filter to k=v (repeatable)'

# ── Subcommands ────────────────────────────────────────────────────────
complete -c pty -n __pty_needs_command -a run -d 'Create a session and attach'
complete -c pty -n __pty_needs_command -a attach -d 'Attach to an existing session'
complete -c pty -n __pty_needs_command -a a -d 'Attach to an existing session'
complete -c pty -n __pty_needs_command -a machine-attach-v2 -d 'Headless framed duplex attach for terminal hosts'
complete -c pty -n __pty_needs_command -a exec -d 'Replace the current session process'
complete -c pty -n __pty_needs_command -a peek -d 'Print current screen (or follow / wait-for-text)'
complete -c pty -n __pty_needs_command -a send -d 'Send text or key events'
complete -c pty -n __pty_needs_command -a events -d 'Follow event log'
complete -c pty -n __pty_needs_command -a list -d 'List sessions'
complete -c pty -n __pty_needs_command -a ls -d 'List sessions'
complete -c pty -n __pty_needs_command -a stats -d 'Live CPU / memory / PIDs'
complete -c pty -n __pty_needs_command -a restart -d 'SIGTERM + respawn'
complete -c pty -n __pty_needs_command -a kill -d 'SIGTERM a running session'
complete -c pty -n __pty_needs_command -a recover -d 'Rebind a supporting live daemon after registry unlink'
complete -c pty -n __pty_needs_command -a rm -d 'Remove exited metadata'
complete -c pty -n __pty_needs_command -a remove -d 'Remove exited metadata'
complete -c pty -n __pty_needs_command -a gc -d 'Reconciliation pass'
complete -c pty -n __pty_needs_command -a tag -d 'Read / write tags on one session'
complete -c pty -n __pty_needs_command -a tag-multi -d 'Bulk tag ops across sessions'
complete -c pty -n __pty_needs_command -a emit -d 'Publish a user.* event'
complete -c pty -n __pty_needs_command -a rename -d 'Set / show / clear displayName'
complete -c pty -n __pty_needs_command -a metadata -d 'Atomically patch presentation metadata by stable id'
complete -c pty -n __pty_needs_command -a up -d 'Start sessions from pty.toml'
complete -c pty -n __pty_needs_command -a down -d 'Stop sessions from pty.toml'
complete -c pty -n __pty_needs_command -a test -d 'Run the pty test suite (vitest)'
complete -c pty -n __pty_needs_command -a remote-serve -d 'Serve remote access control protocol'
complete -c pty -n '__pty_using_command run' -l detach -s d -d 'Create in the background (detached)'
complete -c pty -n '__pty_using_command run' -l attach -s a -d 'Create OR attach if id already exists'
complete -c pty -n '__pty_using_command run' -l ephemeral -s e -d 'Ephemeral: auto-remove metadata on clean exit'
complete -c pty -n '__pty_using_command run' -l id -d 'Pin on-disk id (charset-validated)'
complete -c pty -n '__pty_using_command run' -l name -d 'Display label (trimmed, single-line, ≤ 160 Unicode scalars)'
complete -c pty -n '__pty_using_command run' -l no-display-name -d 'Skip the auto-generated label'
complete -c pty -n '__pty_using_command run' -l tag -d 'Tag session (k=v, repeatable)'
complete -c pty -n '__pty_using_command run' -l env -d 'Overlay child environment (KEY=VALUE, repeatable)'
complete -c pty -n '__pty_using_command run' -l unset-env -d 'Remove inherited environment key (repeatable)'
complete -c pty -n '__pty_using_command run' -l cwd -d 'Working directory'
complete -c pty -n '__pty_using_command run' -l isolate-env -d 'Scrub env to a safe allow-list'
complete -c pty -n '__pty_using_command run' -l force -d 'Create even from inside another pty'
complete -c pty -n '__pty_using_command attach a' -l auto-restart -s r -d 'Auto-restart if the session is exited'
complete -c pty -n '__pty_using_command attach a' -l no-restart -d 'Attach only; never prompt or restart an exited session'
complete -c pty -n '__pty_using_command attach a' -l force -d 'Attach even from inside another pty'
complete -c pty -n '__pty_using_command attach a' -l remote -d 'Attach a session on a fabric peer'
complete -c pty -n '__pty_using_command attach a' -l attach-stream-fd-v1 -x -d 'Write framed machine events to an inherited fd'
complete -c pty -n '__pty_using_command attach a' -a '(__pty_sessions)' -d 'Session'
complete -c pty -n '__pty_using_command exec' -F
complete -c pty -n '__pty_using_command peek' -l follow -s f -d 'Follow output read-only'
complete -c pty -n '__pty_using_command peek' -l plain -d 'Plain text (no ANSI)'
complete -c pty -n '__pty_using_command peek' -l full -d 'Include full scrollback'
complete -c pty -n '__pty_using_command peek' -l wait -d 'Wait until text appears'
complete -c pty -n '__pty_using_command peek' -l timeout -s t -d 'Timeout (seconds) for --wait'
complete -c pty -n '__pty_using_command peek' -l remote -d 'Peek a session on a fabric peer'
complete -c pty -n '__pty_using_command peek' -a '(__pty_sessions)' -d 'Session'
complete -c pty -n '__pty_using_command send' -l seq -d 'Ordered chunk / key event (repeatable)'
complete -c pty -n '__pty_using_command send' -l with-delay -d 'Delay between --seq items (sec)'
complete -c pty -n '__pty_using_command send' -l paste -d 'Wrap in bracketed-paste markers'
complete -c pty -n '__pty_using_command send' -l remote -d 'Send to a session on a fabric peer'
complete -c pty -n '__pty_using_command send' -a '(__pty_sessions)' -d 'Session'
complete -c pty -n '__pty_using_command events' -l all -d 'Follow every session, interleaved'
complete -c pty -n '__pty_using_command events' -l recent -d 'Print recent + exit'
complete -c pty -n '__pty_using_command events' -l json -d 'Emit JSON'
complete -c pty -n '__pty_using_command events' -l wait -d 'Wait for a specific event type'
complete -c pty -n '__pty_using_command events' -l timeout -s t -d 'Timeout (seconds) for --wait'
complete -c pty -n '__pty_using_command events' -a '(__pty_sessions)' -d 'Session'
complete -c pty -n '__pty_using_command list ls' -l json -d 'Emit JSON'
complete -c pty -n '__pty_using_command list ls' -l tags -d 'Include internal bookkeeping tags'
complete -c pty -n '__pty_using_command list ls' -l filter-tag -d 'Filter to k=v (repeatable, ALL match)'
complete -c pty -n '__pty_using_command list ls' -l remote -d 'Include remote sessions via pty-relay'
complete -c pty -n '__pty_using_command list ls' -l status -x -a 'running exited vanished' -d 'Filter by status'
complete -c pty -n '__pty_using_command list ls' -l older-than -d 'Only sessions older than a duration'
complete -c pty -n '__pty_using_command list ls' -l newer-than -d 'Only sessions newer than a duration'
complete -c pty -n '__pty_using_command list ls' -l summary -d 'One-line count summary instead of the list'
complete -c pty -n '__pty_using_command stats' -l json -d 'Emit JSON'
complete -c pty -n '__pty_using_command stats' -l all -d 'Include every session'
complete -c pty -n '__pty_using_command stats' -a '(__pty_sessions)' -d 'Session'
complete -c pty -n '__pty_using_command restart' -l yes -s y -d 'Skip confirmation'
complete -c pty -n '__pty_using_command restart' -l force -d 'Attach after restart even from inside another pty'
complete -c pty -n '__pty_using_command restart' -a '(__pty_sessions)' -d 'Session'
complete -c pty -n '__pty_using_command kill' -a '(__pty_sessions)' -d 'Session'
complete -c pty -n '__pty_using_command recover' -l snapshot -d 'Captured capability-bearing metadata file'
complete -c pty -n '__pty_using_command rm remove' -a '(__pty_sessions)' -d 'Session'
complete -c pty -n '__pty_using_command gc' -l dry-run -s n -d 'Preview without changing anything'
complete -c pty -n '__pty_using_command gc' -l idle-days -d 'Reap permanents with no attach in N days'
complete -c pty -n '__pty_using_command gc' -l fast-fail-window -d 'Fast-fail window (seconds; default 60)'
complete -c pty -n '__pty_using_command gc' -l fast-fail-limit -d 'Consecutive fast fails before flapping (default 3)'
complete -c pty -n '__pty_using_command gc' -l print-launchd-plist -d 'Emit a launchd plist that runs pty gc'
complete -c pty -n '__pty_using_command gc' -l interval -d 'Plist StartInterval seconds (default 30)'
complete -c pty -n '__pty_using_command tag' -l rm -d 'Remove tag key (repeatable)'
complete -c pty -n '__pty_using_command tag' -a '(__pty_sessions)' -d 'Session'
complete -c pty -n '__pty_using_command tag-multi' -l all -d 'Selector: every session'
complete -c pty -n '__pty_using_command tag-multi' -l filter-tag -d 'Selector: k=v (repeatable)'
complete -c pty -n '__pty_using_command tag-multi' -l rm -d 'Remove tag key (repeatable)'
complete -c pty -n '__pty_using_command tag-multi' -l json -d 'Emit JSON'
complete -c pty -n '__pty_using_command tag-multi' -l yes -s y -d 'Confirm --all + write'
complete -c pty -n '__pty_using_command tag-multi' -a '(__pty_sessions)' -d 'Session'
complete -c pty -n '__pty_using_command emit' -l json -d 'JSON payload'
complete -c pty -n '__pty_using_command emit' -l text -d 'Text payload'
complete -c pty -n '__pty_using_command emit' -a '(__pty_sessions)' -d 'Session'
complete -c pty -n '__pty_using_command rename' -l show -d 'Print current displayName'
complete -c pty -n '__pty_using_command rename' -l clear -d 'Remove displayName'
complete -c pty -n '__pty_using_command rename' -a '(__pty_sessions)' -d 'Session'
complete -c pty -n '__pty_using_command metadata' -l id -d 'Exact stable session id'
complete -c pty -n '__pty_using_command metadata' -x -a 'patch' -d 'Value'
complete -c pty -n '__pty_using_command up' -F
complete -c pty -n '__pty_using_command down' -F
complete -c pty -n '__pty_using_command test' -l t -d 'Run matching tests'
complete -c pty -n '__pty_using_command test' -x -a 'watch' -d 'Value'
complete -c pty -n '__pty_using_command remote-serve' -l stdio -d 'On-demand: serve one connection over stdio'
complete -c pty -n '__pty_using_command remote-serve' -l socket -d 'Listening daemon: bind a Unix socket'
